[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
nom = "7.1.3"
regex = "1.11.1"

# RUSTFLAGS="-Clinker=rust-lld.exe -Ctarget-cpu=native" cargo run --profile dev
